// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChangeTipController from "./change_tip_controller"
application.register("change-tip", ChangeTipController)

import FlipPhrasesController from "./flip_phrases_controller"
application.register("flip-phrases", FlipPhrasesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuizController from "./quiz_controller"
application.register("quiz", QuizController)
